# Generated by Django 3.0.7 on 2020-07-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Portfolio', max_length=100)),
                ('url', models.URLField(default='http://localhost:8000')),
                ('image', models.URLField(default='http://localhost:8000')),
            ],
        ),
    ]
